apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-app
  labels:
    app: lab4
    component: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab4
      component: app
  template:
    metadata:
      labels:
        app: lab4
        component: app
    spec:
      volumes:
        - name: app-data
          emptyDir: {}          # volume для /data

      initContainers:
        - name: init-db
          image: lab4-app:1.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: lab4-app-config
            - secretRef:
                name: lab4-app-secret
          volumeMounts:
            - name: app-data
              mountPath: /data
          command: ["python", "init_db.py"]

      containers:
        - name: app
          image: lab4-app:1.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: lab4-app-config
            - secretRef:
                name: lab4-app-secret
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: app-data
              mountPath: /data

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /db-ping       # эндпоинт, который ходит в БД
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
